# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.merchList = QtWidgets.QScrollArea(self.centralwidget)
        self.merchList.setWidgetResizable(True)
        self.merchList.setAlignment(QtCore.Qt.AlignCenter)
        self.merchList.setObjectName("merchList")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 620, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.merchBox1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.merchBox1.setObjectName("merchBox1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.merchBox1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 581, 152))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.merchImage1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.merchImage1.setMinimumSize(QtCore.QSize(150, 150))
        self.merchImage1.setAlignment(QtCore.Qt.AlignCenter)
        self.merchImage1.setObjectName("merchImage1")
        self.horizontalLayout_2.addWidget(self.merchImage1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.nameLabel1.setObjectName("nameLabel1")
        self.verticalLayout.addWidget(self.nameLabel1)
        self.merchDesc1 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_2)
        self.merchDesc1.setObjectName("merchDesc1")
        self.verticalLayout.addWidget(self.merchDesc1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.RemainingLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.RemainingLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.RemainingLabel1.setObjectName("RemainingLabel1")
        self.verticalLayout_2.addWidget(self.RemainingLabel1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.merchNum = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.merchNum.setMinimum(1)
        self.merchNum.setObjectName("merchNum")
        self.horizontalLayout.addWidget(self.merchNum)
        self.BuyButton1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.BuyButton1.setObjectName("BuyButton1")
        self.horizontalLayout.addWidget(self.BuyButton1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addWidget(self.merchBox1)
        self.merchList.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.merchList)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuUser = QtWidgets.QMenu(self.menubar)
        self.menuUser.setObjectName("menuUser")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuUser.addAction(self.actionLogin)
        self.menuUser.addSeparator()
        self.menuUser.addAction(self.actionLogout)
        self.menuQuit.addAction(self.actionQuit)
        self.menubar.addAction(self.menuQuit.menuAction())
        self.menubar.addAction(self.menuUser.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nothing Shop"))
        self.merchBox1.setTitle(_translate("MainWindow", "Merch Name"))
        self.merchImage1.setText(_translate("MainWindow", "Image"))
        self.nameLabel1.setText(_translate("MainWindow", "Merch Name"))
        self.merchDesc1.setPlaceholderText(_translate("MainWindow", "Merch description"))
        self.RemainingLabel1.setText(_translate("MainWindow", "Remaining: 0"))
        self.BuyButton1.setText(_translate("MainWindow", "Buy"))
        self.menuUser.setTitle(_translate("MainWindow", "User"))
        self.menuQuit.setTitle(_translate("MainWindow", "File"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

